### DISCUSSION TITLE
使用 Docker 部署简悦同步助手 · 命令行

### DISCUSSION THREAD

**Discussion by jimlee2048** [Kenshin/simpread#4312] [同步助手]
> 同步助手 · 命令行现已提供 Docker 镜像，允许通过 `docker` 命令或使用  `docker-compose` 快捷部署，习惯了使用 Docker 部署服务的话，可以试试此方式。

使用 Docker 部署同步助手命令行，你可以：

- 使用提供的多平台镜像，方便在你的 arm 树莓派/ m1 mac / 软路由 / 群晖上部署。
- 隔离、统一的运行容器，避免污染宿主机环境，同时也能避免在不同平台上部署可能存在的奇怪问题。
- 通过 Docker 的 CLI，随时查看同步助手命令行的运行状态，方便进行日志查看、版本更新、停止/重启等维护操作。
- 使用`docker-compose`持久化你的配置参数，便利服务的部署与后续迁移。
- 配合简悦未来 [自定义同步助手的服务地址](https://github.com/Kenshin/simpread/issues/4247#issuecomment-1193228369) 的 Feature，实现同步助手的远程部署。
- 配合其他 Docker 镜像，实现更多进阶玩法，请参见下方的进阶使用。

> **注意：** 受当前版本简悦(v2.2.0)的限制， Docker 版的同步助手暂时只适合用作本机部署的用途，不适合作为SaaS服务部署在远程服务器，请参见 [远端部署同步助手](https://github.com/Kenshin/simpread/discussions/4312#discussioncomment-3303682)。

本文将介绍如何使用 Docker 部署简悦同步助手 · 命令行，让我们开始吧：

## 快速部署

使用 Docker 部署非常简单，这里推荐使用 `docker-compose` 进行部署：

首先，根据需要，创建并进入用于存放同步助手数据的文件夹，这里以 `~/simpread-sync` 为例：

```shell
cd ~
mkdir simpread-sync
cd simpread-sync
```

在创建好的文件夹中，新建文件 `docker-compose.yml`，文件内容如下：

```yaml
version: '3'

services:
  simpread-sync:
    image: ghcr.io/j1g5awi/simpread-sync:master
    container_name: simpread-sync
    environment:
      - TZ=Asia/Shanghai
      - SYNC_PATH=/data
      - OUTPUT_PATH=/data/output
    ports:
      - 7026:7026
    volumes:
      - ./data:/data # 同步助手&简悦配置文件保存路径
      - ./output:/data/output # 导出文章保存路径
    restart: unless-stopped

```

> 如果你正在小闪存的设备上部署（如 OpenWrt 软路由），在可用磁盘空间不足的情况下，你可能需要使用`alpine`分支的镜像，请参见 [关于 Docker 镜像](https://github.com/Kenshin/simpread/discussions/4312#discussioncomment-3303638)

> 如果需要自定义导出路径/配置邮件服务，请参考 [修改同步助手暴露的端口号](https://github.com/Kenshin/simpread/discussions/4312#discussioncomment-3303650)

文件保存后，在`docker-compose.yml`所在目录下，使用命令行启动同步助手容器：

```shell
docker-compose up -d
```

容器启动后，参考[新手教程 - 如何安装和配置同步助手](https://github.com/Kenshin/simpread/discussions/2754)，在简悦插件设置页面授权验证后，开启自动同步并覆盖同步助手本地配置文件。

![](https://user-images.githubusercontent.com/81074/131609221-5f4b2b21-90c6-4e85-b7cd-fb87c7abde0d.png)

![](https://user-images.githubusercontent.com/81074/131610074-1bb5f348-3771-4dd1-97ba-8a37edf05943.png)

![](https://user-images.githubusercontent.com/81074/131610221-815f8c46-09a7-4c8f-b9f7-8d591fcbf0a9.png)

完成！现在试试看同步助手是否能够正常工作，默认导出的文件将在同步助手数据文件夹下的`output`文件夹中。

> 如果你需要修改导出文件夹，请参考[自定义同步助手导出文章的保存路径](https://github.com/Kenshin/simpread/discussions/4312#discussioncomment-3303674)

## 环境变量说明

| 环境变量                | 描述                                                         | 默认值                            |
| ----------------------- | ------------------------------------------------------------ | --------------------------------- |
| TZ                      | 容器所使用的时区                                             |                                   |
| LISTEN_PORT             | **容器内**同步助手的监听端口，<br />**一般无需修改**，如需自定义暴露端口，请直接修改docker容器的端口映射（参见[修改同步助手暴露的端口号](https://github.com/Kenshin/simpread/discussions/4312#discussioncomment-3303650)） | 7026                              |
| SYNC_PATH               | **容器内**同步助手的数据文件目录，用于存放自动同步下来的简悦的配置文件<br />**必填项，一般无需修改**，如需自定义目录位置，请直接修改docker容器的目录挂载（参考[自定义同步助手导出文章的保存路径](https://github.com/Kenshin/simpread/discussions/4312#discussioncomment-3303674)） | /data                             |
| OUTPUT_PATH             | **容器内**同步助手导出文件的默认文件夹<br />**一般无需修改**，如需自定义目录位置，请直接修改docker容器的目录挂载（参见[自定义同步助手导出文章的保存路径](https://github.com/Kenshin/simpread/discussions/4312#discussioncomment-3303674)） | `SYNC_PATH`下的下的 output 文件夹 |
| AUTO_REMOVE             | 是否自动删除旧文件，参见[同步助手-导出服务-删除旧文件](http://ksria.com/simpread/docs/#/Sync?id=删除旧文件) | Fasle                             |
| SMTP_HOST               | 同步助手邮件服务使用的 SMTP 服务器地址                       |                                   |
| SMTP_PORT               | 同步助手邮件服务联系 SMTP 服务器使用的端口号 | 465                               |
| SMTP_USERNAME           | 同步助手邮件服务使用的 SMTP 用户名（一般为发件邮箱地址）     |                                   |
| SMTP_PASSWORD           | 同步助手邮件服务使用的 SMTP 密码                             |                                   |
| MAIL_TITLE              | 同步助手发送邮件时使用的邮件标题格式                         | [简悦] - {{title}}                |
| MAIL_RECEIVER           | 同步助手邮件服务要发送到的收件邮箱地址                       |                                   |
| MAIL_KINDLE             | 同步助手邮件服务要发送到的Kindle邮箱地址                     |                                   |
| OUTPUT_PATH_{extension} | **容器内**后缀为`{extension}`的文件导出到的特定目录，请参见[自定义同步助手导出文章的保存路径](https://github.com/Kenshin/simpread/discussions/4312#discussioncomment-3303674)<br />当前同步助手命令行支持的后缀名：<br />- `html`：`OUTPUT_PATH_HTML`<br />- `md`: `OUTPUT_PATH_MD`<br />- `epub`: `OUTPUT_PATH_EPUB`<br />- `textbundle`: `OUTPUT_PATH_TEXTBUNDLE` |                                   |

### 关于 Docker 镜像

https://github.com/Kenshin/simpread/discussions/4312#discussioncomment-3303638

### 修改同步助手暴露的端口号

https://github.com/Kenshin/simpread/discussions/4312#discussioncomment-3303650

### 配置邮件服务

https://github.com/Kenshin/simpread/discussions/4312#discussioncomment-3303676

### 管理同步助手容器

操作前需先进入配置同步助手的 `docker-compose.yml`所在目录

查看容器运行状态

```shell
docker-compose status
```

停止容器

```shell
docker-compose down
```

重启容器

```shell
docker-compose restart
```

查看容器最新10条日志

```shell
docker-compose logs simpread-sync --tail 10
```

你也可以使用 [Portainer](https://www.portainer.io/)进行管理，这里不再赘述。

### 更新同步助手

手动更新同步助手非常简单，重新执行启动命令即可：

```shell
docker-compose up -d
```

如果检测到更新，容器会自动下载最新镜像并自动重启。

你也可以使用 [watchtower](https://github.com/containrrr/watchtower)实现自动更新，这里不再赘述。

### 远端部署同步助手

https://github.com/Kenshin/simpread/discussions/4312#discussioncomment-3303682

### 补充说明

https://github.com/Kenshin/simpread/discussions/4312#discussioncomment-3389223

## 关联阅读

- [Feature Request: Provide Docker Image · Issue #1 · j1g5awi/simpread-sync (github.com)](https://github.com/j1g5awi/simpread-sync/issues/1)
- [新手教程: 如何安装和配置同步助手 · Discussion #2754 · Kenshin/simpread (github.com)](https://github.com/Kenshin/simpread/discussions/2754)
- [将简悦 · 同步助手部署在远程（ SaasS 化 ），方便多个扩展端共用一个同步助手 · Discussion #3898 · Kenshin/simpread (github.com)](https://github.com/Kenshin/simpread/discussions/3898)
- [Feature Request: 自定义同步助手的服务地址 · Issue #4247 · Kenshin/simpread (github.com)](https://github.com/Kenshin/simpread/issues/4247)

**Comment by Kenshin** [comment]
# 关于 Docker 镜像

本镜像支持`amd64`与`arm64`，docker在拉取时会自动选择适配当前架构的镜像。

由于需要安装 pandoc （导出 Epub）和 wkhtml2pdf（导出PDF），所以镜像主分支基于更方便的 debian 打包，镜像体积较大（约700m）。对于在OpenWrt等小闪存环境中使用的用户，请注意你是否有足够的磁盘空间存放镜像。

```yaml
services:
  simpread-sync:
    image: ghcr.io/j1g5awi/simpread-sync:master
```

如果不需要导出 Epub 和定制导出 PDF 的功能，可以选用基于 alpine 打包的，体积较小的镜像分支 `alpine`，只需修改 `docker-compose.yml`中镜像地址最后的分支名即可：

```yaml
services:
  simpread-sync:
    image: ghcr.io/j1g5awi/simpread-sync:alpine
```

**Comment by Kenshin** [comment]
# 修改同步助手暴露的端口号

同步助手默认暴露以下端口号：

- `7026`：用于连接简悦浏览器插件

示例：希望修改暴露的同步助手的监听端口为`17026`.

## 容器使用docker默认的`bridge`网络模式

> 为避免混淆，请不要直接修改环境变量`LISTEN_PORT`的默认值。

没有特别指定的话，docker默认使用的是`bridge`网络模式。

在该情况下，修改`docker-compose.yml`中定义的容器端口映射规则即可：

> docker容器端口映射规则格式： `<宿主机实际外部端口号>`:`<容器内部端口号>`

```yaml
services:
  simpread-sync:
    ports:
      - 17026:7026
```

## 容器使用`host`网络模式

直接添加环境变量`LISTEN_PORT`：
```yaml
services:
  simpread-sync:
    network_mode: "host"
    environment:
      - LISTEN_PORT=17026
```

**Reply by Kenshin** [reply]
Done

**Comment by Kenshin** [comment]
# 自定义同步助手导出文章的保存路径

> 为避免混淆，不建议直接修改路径相关的环境变量：`OUTPUT_PATH` 与 `SYNC_PATH` 的默认值。

## 修改导出文章的默认路径

默认情况下，导出的所有文章都会保存在 `SYNC_PATH` 下的 output 文件夹中。

如果需要自定义导出文章的保存路径，请修改 `docker-compose.yml` 中映射到容器内的路径 `/data/output`（`OUTPUT_PATH`的值）的主机实际路径。

示例：将 `/path/to/output` 设为同步助手默认导出文章的路径：

> docker容器路径映射规则格式： `<宿主机实际路径>`:`<容器内部路径>`

```yaml
services:
  simpread-sync:
    volumes:
      - /path/to/output:/data/output # 导出文章保存路径
```

#### 自定义特定格式文件的导出路径（[增强导出](http://ksria.com/simpread/docs/#/Sync?id=%e5%a2%9e%e5%bc%ba%e5%af%bc%e5%87%ba)）

在 `docker-compose.yml` 中：

- 先添加对应文件后缀名的变量 `OUTPUT_PATH_{extension}`，值设为容器内的导出路径（自定义）

- 随后，添加路径映射规则，将宿主机实际路径映射到容器内的该导出路径中

示例：

- 设置导出markdown格式的文章（文件后缀为`md`）到宿主机实际路径`/another/path/to/output-md`，设置容器内导出路径为`/output-md`
- 设置导出html格式的文章（文件后缀为`html`）到宿主机实际路径`/another/path/to/output-html`，设置容器内导出路径为`/output-html`

```yaml
services:
  simpread-sync:
    environment:
      - OUTPUT_PATH_MD=/output-md
      - OUTPUT_PATH_HTML=/output-html
    volumes:
      - /another/path/to/output-md:/output-md
      - /another/path/to/output-html:/output-html
```

**Comment by Kenshin** [comment]
# 配置邮件服务

在 `docker-compose.yml` 中添加相关的环境变量即可，请参考[同步助手 - 邮件服务](http://ksria.com/simpread/docs/#/Sync?id=邮件服务)：

```yaml
services:
  simpread-sync:
    environment:
      - SMTP_HOST=
      - SMTP_PORT=465
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - MAIL_TITLE="[简悦] - {{title}}"
      - MAIL_RECEIVER=
      - MAIL_KINDLE=
```
