### ISSUE TITLE
支持自定义文件头部内容

### ISSUE THREAD

**Issue by Quorafind** [Kenshin/simpread#1198]
1. 使用版本——简悦2.0

1. 需求场景——桌面端

2. 需求简写——插件或原生支持自定义文件头

3. 具体需求：

    - 当下载 Markdown 文件时，可以在 Markdown 文件头添加自定义的 YAMLfrontmatter.
      如：
      ```
      Title: 网页标题
      Tag: #知识仓库
      Toc: 
      Link: 网页地址
      Date: 日期时间
      ```
    - 进一步地，支持自定义具体变量，且每次生成 Markdown 文件的时候植入到文件内容的头部

4. 需求原因：
    利用这个自定义的头部，可以在各种 Markdown 笔记软件中检索且筛选相关的笔记
    例如，我现在所用的 Obsidian 支持在软件中筛选相关的笔记，从而起到快速检索知识库的目的。

    类似地，在印象笔记或其它可以利用内容进行筛选的笔记软件中，可以利用正则或其它方式检索一定时间内的标题，具体为利用其中的Date参数。
    

如果开发者比较忙，恳请引路我去研究相应的插件的写法，例如指出相应的 api ，我尽可能做到自行实现不劳扰您。

> 

>
