### ISSUE TITLE
自定义CSS无法起作用

### ISSUE THREAD

**Issue by cdchs99** [Kenshin/simpread#2934]
你好，我在使用简悦的自定义CSS功能时，遇到了一些困难，故想向你请教下。
- 测试网页 
    <https://www.ptwxz.com/html/13/13191/9556827.html>
- HTML代码段
```HTML
<sr-rd-content>
    <div>
        <a href="9554481.html">上一章</a>&nbsp;&nbsp;&nbsp;
        <a href="./">返回目录</a>&nbsp;&nbsp;&nbsp;
        <a href="index.html">下一章</a>&nbsp;&nbsp;&nbsp;
        <a href="http://www.ptwxz.com/bookinfo/13/13191.html" target="_blank">返回书页</a>
    </div>
    ...
</sr-rd-content>
```
- CSS代码段
```CSS
sr-rd-content div {
    text-align: center;
    background-color: pink;
    border: 2px dashed black;
    margin: 0px auto;
}
 sr-rd-content a {
    text-decoration: none;
}
```
- 图片
![image](https://user-images.githubusercontent.com/47968720/136769460-7e7ee8fc-367b-4028-bb84-e67546059c23.png)

- 环境
    - windows 10
    - chrome 94.0.4606.71
    - SimpRead 2.2.0.520

所以，为什么 `text-decoration: none;` 不能将 `a` 里面的超本文引用的下划线隐藏掉呢？
我将这段代码复制到VScode里面，都可以如我预期那般实现呀。
