### ISSUE TITLE
有序列表显示为无序列表

### ISSUE THREAD

**Issue by NihilityT** [Kenshin/simpread#437]
有序列表显示为无序列表
<img src="https://user-images.githubusercontent.com/21163191/51009241-578c6680-158a-11e9-848f-66ab3852f157.png" height="350" /><img src="https://user-images.githubusercontent.com/21163191/51009242-5824fd00-158a-11e9-90eb-d06f813cb943.png" height="350" />
目前通过覆盖样式解决
``` CSS
ol li {
    list-style: unset !important;
}
```
