### ISSUE TITLE
导出PDF方案失效

### ISSUE THREAD

**Issue by Kiss-World** [Kenshin/simpread#5818]
### 描述这个错误

使用简悦导出PDf，主要问题：没法导出所见即所得的PDF。
使用菜单栏的PDF导出，PDF字体永远默认为15px，而不是我设置的阅读模式下的页面。
于是我在帮助中，按照教程配置了pdf的官方提供的配置库。
结果，高级打印功能失效。右侧pDf配置导出仍然存在所见不是所得的情况。

要崩溃了，在qq频道提问也没人搭理。

![image](https://github.com/Kenshin/simpread/assets/44720566/78b3a961-a9ee-4ba7-9d6c-1527b979647c)
![image](https://github.com/Kenshin/simpread/assets/44720566/09371c0f-c367-40ee-8741-2f92852d1476)

### 复现步骤

同上

### 其他相关说明

qq：850020586

### 操作系统

win11

### 浏览器

谷歌最新版

### 发生问题的网址

https://zhuanlan.zhihu.com/p/499697441

**Comment by Kiss-World** [comment]
在新的电脑上测试了纯粹的简悦+同步助手 的基础导出PDF，标题及文章内的标题大小会随着阅读页面的字体大小变化。正文内容不会。
终于舒服了，确认了是软件的bug不是设置问题了。话说简悦这个配置属实复杂。最重要是出了问题都不知道怎么排查。太难了

**Comment by Kenshin** [comment]
问题解决就好。

基础 PDF 调用的浏览器的 PDF 会有一定的问题，比如：无法在 PDF 中标注等，但对于某些用户来说或许没问题。

PS：高级打印方案具有更多的定制化功能 https://github.com/Kenshin/simpread/discussions/3887

PPS：会考虑增加可调试方案，让调查更方便。

**Comment by Kiss-World** [comment]
你好，问题并没有解决哦。我发现问题出在了htmL上，所以我现在是先导出html。然后修改html的字体大小，边距等，然后使用刘浏览器自带的pdf导出。效果非常好。

我的工作流是配合 zotero 使用的，所以我使用简悦的需求就只有一个，就是导出PDF。我记得我半个月前貌似导出还没有问题，忽然有一天就不行了好像。建议作者测试一下。或者我可以配合测试一下。我太需要这个功能好用了。

**Comment by Kiss-World** [comment]
```css
sr-rd-content *,sr-rd-desc,sr-rd-content p,sr-rd-content div  {
    letter-spacing: 10px;
    line-height: 1.6;
    word-spacing: 2px;
    font-size: 25px;
    text-indent: 35px;
    font-weight: 400;

}
/*字间隔没有生效*/
/* 标题 */
sr-rd-title {
    font-size: 40px;
}

sr-rd-content h2{

    font-size: 30px;
}

sr-rd-content h1{

    font-size: 40px;
}

sr-rd-content h3{

    font-size: 25px;
}

sr-rd-content h1, sr-rd-content h2, sr-rd-content h3, sr-rd-content h4, sr-rd-content h5, sr-rd-content h6 {
    font-weight: bold;
    color: #6363ac;
}
/* 列表 */

sr-rd-content ol li, sr-rd-content ul li {
    margin-left: 20px;
    list-style: disc;

}


img {
  max-width: 80%;
}
``` 
我使用高级打印方案的自定义css解决了一部分问题。可惜前端有点菜。希望作者可以提供更多的 css修改模板。
