### ISSUE TITLE
安装Obsidian插件以后无法正常启用「在导入到全文时是否使用md+assets方式」，页面刷新以后设置丢失

### ISSUE THREAD

**Issue by zieglar** [Kenshin/simpread#6404]
### 描述这个错误

1、本机已经成功配置同步助手客户端docker版，`docker-compose.yml`文件内容如下
```
version: '3'

services:
  simpread-sync:
    image: ghcr.io/j1g5awi/simpread-sync:master
    container_name: simpread-sync
    environment:
      - TZ=Asia/Shanghai
      - SYNC_PATH=/data
      - OUTPUT_PATH=/data/output
      - OUTPUT_PATH_MD=/data/output-md
    ports:
      - 7026:7026
    volumes:
      - ./data:/data # 同步助手&简悦配置文件保存路径
      - ./output:/data/output # 导出文章保存路径
      - ./output-md:/data/output-md
    restart: unless-stopped
```
`output-md`及 `/data/output-md`目录均通过软链接链接至 `/Users/zieglar/Dropbox/Obsidian Read/Read/Read`目录
2、Obsidian插件启用Local REST API方案，token设置成功，「导入全文到Obsidian」可以正常输出md文件到Obsidian的Read库下Read目录中
3、在Obsidian选项中配置「在导入到全文时是否使用md+assets方式」及「导出根目录」选项后刷新页面后该选项丢失

### 复现步骤

1.打开[https://juejin.cn/post/7348312569629769765](https://juejin.cn/post/7348312569629769765)，进入阅读模式，进入动作-导入到Obsidian选项
2.打开「在导入到全文时是否使用md+assets方式」
3.配置下方导出根目录为`/Users/zieglar/Dropbox/Obsidian Read/Read/Read`
4.保存，页面提示保存成功
5.关闭配置页面，esc退出阅读模式，刷新当前页面
6.重新进入阅读模式，进入动作-导入到Obsidian选项，「在导入到全文时是否使用md+assets方式」被重置，下方导出根目录被清空
![CleanShot 2024-03-27 at 17 24 48@2x](https://github.com/Kenshin/simpread/assets/514693/f9ac077e-27e8-4554-8d98-9ac121e327b9)

### 其他相关说明

在 「在导入到全文时是否使用md+assets方式」 正常设置后，在导出时可以看到docker容器`simpread-sync`的log正常输出 simpread-sync  | 2024/03/27 15:50:52 save notextbundle: {title}

### 操作系统

macOS 14.4.1 (23E224)

### 浏览器

Arc 1.35.0

### 发生问题的网址

https://juejin.cn/post/7348312569629769765
