### ISSUE TITLE
1.1.4影响原网页显示

### ISSUE THREAD

**Issue by MANSOUL** [Kenshin/simpread#833]
在Chrome中开启模拟器浏览使用rem适配的网页时，受到简悦CSS的影响，导致原网页无法正常显示。影响代码：

```css
@media (pointer:coarse) {
  html {
    font-size: 70% !important;
  }
}
```
